/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analiseartigosia.areaGrafica;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author 'Alisson
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        jButtonVisualizarContribuicao.setVisible(false);
        jButtonVisualizarInstituicoesAutores.setVisible(false);
        jButtonVisualizarMetodologia.setVisible(false);
        jButtonVisualizarObjetivos.setVisible(false);
        jButtonVisualizarProblema.setVisible(false);
        jButtonVisualizarReferencias.setVisible(false);
        jButtonVisualizarResultado.setVisible(false);
        jButtonVisualizarTermos.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelCriadores = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelSelecaoArquivo = new javax.swing.JLabel();
        jTextFieldSelecaoArquivo = new javax.swing.JTextField();
        jButtonSelecionar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jCheckBoxStopWords = new javax.swing.JCheckBox();
        jCheckBoxTermos = new javax.swing.JCheckBox();
        jCheckBoxReferencias = new javax.swing.JCheckBox();
        jCheckBoxInstituicoesAutores = new javax.swing.JCheckBox();
        jCheckBoxObjetivos = new javax.swing.JCheckBox();
        jCheckBoxProblema = new javax.swing.JCheckBox();
        jCheckBoxMetodologia = new javax.swing.JCheckBox();
        jCheckBoxContribuicao = new javax.swing.JCheckBox();
        jButtonAnalisarArtigo = new javax.swing.JButton();
        jButtonVisualizarResultado = new javax.swing.JButton();
        jButtonVisualizarTermos = new javax.swing.JButton();
        jButtonVisualizarReferencias = new javax.swing.JButton();
        jButtonVisualizarInstituicoesAutores = new javax.swing.JButton();
        jButtonVisualizarProblema = new javax.swing.JButton();
        jButtonVisualizarObjetivos = new javax.swing.JButton();
        jButtonVisualizarMetodologia = new javax.swing.JButton();
        jButtonVisualizarContribuicao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Processamento de Linguagem Natural - Inteligencia Artificial");
        setMinimumSize(new java.awt.Dimension(800, 600));

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Análise de Artigos Científicos");
        jLabelTitulo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabelTitulo, java.awt.BorderLayout.PAGE_START);

        jLabelCriadores.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCriadores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCriadores.setText("Desenvolvido por Alisson R. Svaigen, Filipe G. Genu e Lailla M. S. Bine");
        jLabelCriadores.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelCriadores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabelCriadores, java.awt.BorderLayout.PAGE_END);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));

        jLabelSelecaoArquivo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelSelecaoArquivo.setText("Selecione o arquivo PDF a ser analisado:");

        jTextFieldSelecaoArquivo.setEditable(false);

        jButtonSelecionar.setIcon(new javax.swing.ImageIcon("C:\\Users\\'Alisson\\Documents\\NetBeansProjects\\AnaliseArtigosIA\\AnaliseArtigosIA\\src\\analiseartigosia\\icones\\search.png")); // NOI18N
        jButtonSelecionar.setText("Selecionar");
        jButtonSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelecionarActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de operações"));
        jPanel2.setEnabled(false);

        jCheckBoxStopWords.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCheckBoxStopWords.setSelected(true);
        jCheckBoxStopWords.setText("Retirar Stop Words");
        jCheckBoxStopWords.setEnabled(false);
        jCheckBoxStopWords.setName(""); // NOI18N
        jCheckBoxStopWords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxStopWordsActionPerformed(evt);
            }
        });

        jCheckBoxTermos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCheckBoxTermos.setText("Identificar 10 termos mais utilizados");
        jCheckBoxTermos.setEnabled(false);
        jCheckBoxTermos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTermosActionPerformed(evt);
            }
        });

        jCheckBoxReferencias.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCheckBoxReferencias.setText("Extrair Referências");
        jCheckBoxReferencias.setEnabled(false);
        jCheckBoxReferencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxReferenciasActionPerformed(evt);
            }
        });

        jCheckBoxInstituicoesAutores.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCheckBoxInstituicoesAutores.setText("Identificar Instituições / Autores");
        jCheckBoxInstituicoesAutores.setEnabled(false);
        jCheckBoxInstituicoesAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxInstituicoesAutoresActionPerformed(evt);
            }
        });

        jCheckBoxObjetivos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCheckBoxObjetivos.setText("Identificar Objetivos");
        jCheckBoxObjetivos.setEnabled(false);
        jCheckBoxObjetivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxObjetivosActionPerformed(evt);
            }
        });

        jCheckBoxProblema.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCheckBoxProblema.setText("Identificar Problema ");
        jCheckBoxProblema.setEnabled(false);
        jCheckBoxProblema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxProblemaActionPerformed(evt);
            }
        });

        jCheckBoxMetodologia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCheckBoxMetodologia.setText("Identificar Metodologia");
        jCheckBoxMetodologia.setEnabled(false);
        jCheckBoxMetodologia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMetodologiaActionPerformed(evt);
            }
        });

        jCheckBoxContribuicao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCheckBoxContribuicao.setText("Identificar Contribuição");
        jCheckBoxContribuicao.setEnabled(false);
        jCheckBoxContribuicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxContribuicaoActionPerformed(evt);
            }
        });

        jButtonAnalisarArtigo.setIcon(new javax.swing.ImageIcon("C:\\Users\\'Alisson\\Documents\\NetBeansProjects\\AnaliseArtigosIA\\AnaliseArtigosIA\\src\\analiseartigosia\\icones\\glasses.png")); // NOI18N
        jButtonAnalisarArtigo.setText("Analisar Artigo");
        jButtonAnalisarArtigo.setEnabled(false);

        jButtonVisualizarResultado.setText("Visualizar Resultado");
        jButtonVisualizarResultado.setEnabled(false);
        jButtonVisualizarResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisualizarResultadoActionPerformed(evt);
            }
        });

        jButtonVisualizarTermos.setText("Visualizar Resultado");
        jButtonVisualizarTermos.setEnabled(false);
        jButtonVisualizarTermos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisualizarTermosActionPerformed(evt);
            }
        });

        jButtonVisualizarReferencias.setText("Visualizar Resultado");
        jButtonVisualizarReferencias.setEnabled(false);
        jButtonVisualizarReferencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisualizarReferenciasActionPerformed(evt);
            }
        });

        jButtonVisualizarInstituicoesAutores.setText("Visualizar Resultado");
        jButtonVisualizarInstituicoesAutores.setEnabled(false);
        jButtonVisualizarInstituicoesAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisualizarInstituicoesAutoresActionPerformed(evt);
            }
        });

        jButtonVisualizarProblema.setText("Visualizar Resultado");
        jButtonVisualizarProblema.setEnabled(false);
        jButtonVisualizarProblema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisualizarProblemaActionPerformed(evt);
            }
        });

        jButtonVisualizarObjetivos.setText("Visualizar Resultado");
        jButtonVisualizarObjetivos.setEnabled(false);
        jButtonVisualizarObjetivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisualizarObjetivosActionPerformed(evt);
            }
        });

        jButtonVisualizarMetodologia.setText("Visualizar Resultado");
        jButtonVisualizarMetodologia.setEnabled(false);
        jButtonVisualizarMetodologia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisualizarMetodologiaActionPerformed(evt);
            }
        });

        jButtonVisualizarContribuicao.setText("Visualizar Resultado");
        jButtonVisualizarContribuicao.setEnabled(false);
        jButtonVisualizarContribuicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisualizarContribuicaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jCheckBoxStopWords, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonVisualizarResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jCheckBoxTermos, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonVisualizarTermos, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jCheckBoxReferencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonVisualizarReferencias, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jCheckBoxInstituicoesAutores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonVisualizarInstituicoesAutores, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jCheckBoxObjetivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonVisualizarObjetivos, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jCheckBoxProblema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonVisualizarProblema, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jCheckBoxMetodologia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonVisualizarMetodologia, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jCheckBoxContribuicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonVisualizarContribuicao, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonAnalisarArtigo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxStopWords)
                    .addComponent(jButtonVisualizarResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxTermos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonVisualizarTermos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxReferencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonVisualizarReferencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxInstituicoesAutores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonVisualizarInstituicoesAutores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxObjetivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonVisualizarObjetivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxProblema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonVisualizarProblema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxMetodologia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonVisualizarMetodologia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxContribuicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonVisualizarContribuicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButtonAnalisarArtigo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelSelecaoArquivo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldSelecaoArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSelecionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(291, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonSelecionar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelSelecaoArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldSelecaoArquivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(816, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelecionarActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setApproveButtonToolTipText("Selecionar");
        fileChooser.setApproveButtonText("Selecionar");
        fileChooser.setDialogTitle("Selecione um arquivo");
        int userSelection = fileChooser.showSaveDialog(this);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            jTextFieldSelecaoArquivo.setText(fileChooser.getSelectedFile().getPath());
            jPanel2.setEnabled(true);
            ativaCamposDeAnalise();
        }        
    }//GEN-LAST:event_jButtonSelecionarActionPerformed

    private void jButtonVisualizarContribuicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisualizarContribuicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVisualizarContribuicaoActionPerformed

    private void jButtonVisualizarMetodologiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisualizarMetodologiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVisualizarMetodologiaActionPerformed

    private void jButtonVisualizarObjetivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisualizarObjetivosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVisualizarObjetivosActionPerformed

    private void jButtonVisualizarProblemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisualizarProblemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVisualizarProblemaActionPerformed

    private void jButtonVisualizarInstituicoesAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisualizarInstituicoesAutoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVisualizarInstituicoesAutoresActionPerformed

    private void jButtonVisualizarReferenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisualizarReferenciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVisualizarReferenciasActionPerformed

    private void jButtonVisualizarTermosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisualizarTermosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVisualizarTermosActionPerformed

    private void jButtonVisualizarResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisualizarResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVisualizarResultadoActionPerformed

    private void jCheckBoxContribuicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxContribuicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxContribuicaoActionPerformed

    private void jCheckBoxMetodologiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMetodologiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxMetodologiaActionPerformed

    private void jCheckBoxProblemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxProblemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxProblemaActionPerformed

    private void jCheckBoxObjetivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxObjetivosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxObjetivosActionPerformed

    private void jCheckBoxInstituicoesAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxInstituicoesAutoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxInstituicoesAutoresActionPerformed

    private void jCheckBoxReferenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxReferenciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxReferenciasActionPerformed

    private void jCheckBoxTermosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTermosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxTermosActionPerformed

    private void jCheckBoxStopWordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxStopWordsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxStopWordsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnalisarArtigo;
    private javax.swing.JButton jButtonSelecionar;
    private javax.swing.JButton jButtonVisualizarContribuicao;
    private javax.swing.JButton jButtonVisualizarInstituicoesAutores;
    private javax.swing.JButton jButtonVisualizarMetodologia;
    private javax.swing.JButton jButtonVisualizarObjetivos;
    private javax.swing.JButton jButtonVisualizarProblema;
    private javax.swing.JButton jButtonVisualizarReferencias;
    private javax.swing.JButton jButtonVisualizarResultado;
    private javax.swing.JButton jButtonVisualizarTermos;
    private javax.swing.JCheckBox jCheckBoxContribuicao;
    private javax.swing.JCheckBox jCheckBoxInstituicoesAutores;
    private javax.swing.JCheckBox jCheckBoxMetodologia;
    private javax.swing.JCheckBox jCheckBoxObjetivos;
    private javax.swing.JCheckBox jCheckBoxProblema;
    private javax.swing.JCheckBox jCheckBoxReferencias;
    private javax.swing.JCheckBox jCheckBoxStopWords;
    private javax.swing.JCheckBox jCheckBoxTermos;
    private javax.swing.JLabel jLabelCriadores;
    private javax.swing.JLabel jLabelSelecaoArquivo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldSelecaoArquivo;
    // End of variables declaration//GEN-END:variables

    private void ativaCamposDeAnalise() {
        jCheckBoxContribuicao.setEnabled(true);
        jCheckBoxInstituicoesAutores.setEnabled(true);
        jCheckBoxMetodologia.setEnabled(true);
        jCheckBoxObjetivos.setEnabled(true);
        jCheckBoxProblema.setEnabled(true);
        jCheckBoxReferencias.setEnabled(true);
        jCheckBoxTermos.setEnabled(true);
        jButtonAnalisarArtigo.setEnabled(true);
    }
}
